FineDust/Extension/NSLayoutConstraint+.swift, FineDust/Statistics/Controller/StatisticsViewController.swift, FineDust/Statistics/View/Value Graph/ValueGraphView.swift, FineDust/Statistics/View/Value Graph/ValueGraphView.xib
=> 통계 막대그래프 애니메이션 관련

FineDust.xcodeproj/project.pbxproj, FineDust/Core Data/CoreDataHelper.swift, FineDust/Core Data/FineDust.xcdatamodeld/FineDust.xcdatamodel/contents, FineDust/Core Data/Intake+.swift, FineDust/Core Data/User+.swift, FineDust/Supporting Files/AppDelegate.swift
- 코어 데이터 모델 정의
- 코어 데이터 래핑
- 첫 실행시 `User` 엔티티에 실행 날짜를 저장하도록 함
코드 사용 예시
```
CoreDataHelper.shared.save(
[User.installedDate: Date()], 
forType: User.self
) { error in
print(error.localizedDescription) 
}
```
```
CoreDataHelper.shared.fetch(forType: User.self) { user, error in
print(user?.installedDate, error.localizedDescription)
}
```
=> Core Data Wrapping

.swiftlint.yml, FineDust.xcodeproj/project.pbxproj, FineDust/Common/Manager/API+FineDust.swift, FineDust/Common/Manager/API.swift, FineDust/Common/Manager/CoreDataManager.swift, FineDust/Common/Manager/LocationManager.swift, FineDust/Common/ProgressIndicator.swift, FineDust/Core Data/CoreData+Intake.swift, FineDust/Core Data/CoreData+User.swift, FineDust/Extension/CALayer+.swift, FineDust/Extension/Date+.swift, FineDust/Extension/NSLayoutAnchor+.swift, FineDust/Extension/NSLayoutConstraint+.swift, FineDust/Extension/NSLayoutDimension+.swift, FineDust/Extension/NSObject+.swift, FineDust/Extension/Notification.Name+.swift, FineDust/Extension/String+.swift, FineDust/Extension/UIAlertController+.swift, FineDust/Extension/UIColor+.swift, FineDust/Extension/UIView+.swift, FineDust/Extension/UIView+NSLayoutAnchor.swift, FineDust/Extension/UIViewController+.swift, FineDust/Model/FineDustInfo.swift, FineDust/Model/GeoInfo.swift, FineDust/Network/Network.swift, FineDust/Statistics/Controller/StatisticsViewController.swift, FineDust/Statistics/View/Ratio Graph/RatioGraphView.swift, FineDust/Statistics/View/Value Graph/ValueGraphView.swift, FineDust/Statistics/View/Value Graph/ValueGraphView.xib, FineDust/Supporting Files/AppDelegate.swift
- @intmain 튜터님의 코드 리뷰를 반영하였습니다.
- 주석 달았습니다.
=> Presto refactoring

FineDust.xcodeproj/project.pbxproj, FineDust/Extension/CALayer+.swift, FineDust/Extension/Date+.swift, FineDust/Network/Network.swift
**Date Extension**
- 기준 날짜의 0시
- 기준 날짜의 23시 59분 59초
- 주어진 날짜의 0시
- 주어진 날짜의 23시 59분 59초
- 프로그레스 인디케이터 동작을 메인쓰레드로 돌림
=> Date 익스텐션++

README.md
이 브랜치는 리드미 같은 문서만 작업합니다
- 리드미 업데이트
=> README + Travis CI Badge

FineDust.xcodeproj/project.pbxproj, FineDustTests/Mock/MockHealthKitManager.swift, FineDustTests/Test/HealthKitServiceManagerTest.swift, FineDustTests/Test/README
findHealthKitValue 함수 수정이 끝난 후 다시 수정하겠습니다.
=> Healthkit testcase 정의했습니다.

FineDust.xcodeproj/project.pbxproj, FineDust/Common/Hour.swift, FineDust/Common/LocationObserver.swift, FineDust/Dust/DustInfoService.swift, FineDust/Extension/Notification+.swift, FineDust/Extension/UIViewController+.swift, FineDust/Location/LocationManager.swift, FineDust/Location/LocationManagerType.swift, FineDust/Statistics/Ratio Graph/RatioGraphView.swift, FineDust/Statistics/Ratio Graph/RatioGraphViewDelegate.swift, FineDust/Statistics/StatisticsViewController.swift, FineDust/Statistics/Value Graph/ValueGraphView.swift, FineDust/Statistics/Value Graph/ValueGraphViewDelegate.swift, FineDust/Supporting Files/AppDelegate.swift, FineDust/Supporting Files/LocationTaskError.swift
- LocationManager에 프로토콜 초기 구현을 통해서 configure할 필요가 없게 하였습니다
=> LocationManager

FineDustTests/Test/HealthKitServiceTest.swift
=> HealthKitServiceTest 수정

FineDust.xcodeproj/project.pbxproj, FineDust/Common/Typealias.swift, FineDust/Dust/DustInfoService.swift, FineDust/Dust/DustInfoServiceType.swift, FineDust/Response/DustResponse.swift
- 돌아가게만 해뒀습니다. 리팩토링은 나중에..
- 미세먼지 값이 `-`로 오는 경우..가 있길래 일단 String으로 파싱하여 저장하고 Int를 가져다 쓸 수 있게끔 했습니다
=> 특정 날짜 구간 내의 미세먼지 및 초미세먼지 시간대별 값 구하기

FineDust/Statistics/StatisticsViewController.swift, FineDust/Statistics/Value Graph/ValueGraphView.swift, FineDust/Statistics/Value Graph/ValueGraphView.xib, FineDust/Statistics/Value Graph/ValueGraphViewDelegate.swift
=> 날짜 선택 기능 제거

FineDust/Core Data/CoreData+User.swift, FineDust/Core Data/CoreDataIntakeManagerType.swift, FineDust/Core Data/CoreDataService.swift, FineDust/Core Data/CoreDataServiceType.swift, FineDust/Core Data/FineDust.xcdatamodeld/FineDust.xcdatamodel/contents, FineDustTests/Test/DustInfoServiceTest.swift
=> 코어데이터 최신 접속 날짜 저장 작업

FineDust.xcodeproj/project.pbxproj, FineDust/Dust/DustInfoService.swift, FineDust/Extension/DateFormatter+.swift, FineDust/Extension/Locale+.swift
DateFormatter+ 정의하고
DustInfoService를 이에 맞게 고쳐보았습니다
=> Dateformatter+

FineDust/HealthKit/HealthKitManager.swift, FineDust/HealthKit/HealthKitManagerType.swift, FineDust/HealthKit/HealthKitService.swift, FineDust/HealthKit/HealthKitServiceType.swift, FineDust/Main/Controller/MainViewController.swift, FineDustTests/Test/HealthKitManagerTests.swift, FineDustTests/Test/IntakeServiceTest.swift
* 아직 날짜별로 걸음거리를 구하는 것 까지는 구현하지 못했습니다.
* MainViewController에 있는 코드는 값이 잘 나오는지 확인하는 임시 코드입니다.
=> 시간별로 걸음 거리를 나타내주는 메소드 구현

FineDust/Core Data/CoreDataService.swift, FineDust/Core Data/CoreDataServiceType.swift, FineDust/Dust/DustInfoService.swift, FineDust/Extension/DateFormatter+.swift
- `DateFormatter.date`가 이미 정의된게 있어서 네이밍을 좀 바꿔봤는데 마땅한게 안떠오르네요
=> 데이트포매터 익스텐션 네이밍 외

FineDust.xcodeproj/project.pbxproj, FineDust/Core Data/CoreDataService.swift, FineDust/Core Data/CoreDataServiceType.swift, FineDust/Dust/DustInfoService.swift
- 최신 접속 날짜 가져오기
- 최신 접속 날짜 저장하기
- 특정 기간 내의 미세먼지 흡입량 가져오기
- 특정 날짜의 미세먼지 흡입량 저장하기
=> CoredataService

FineDust/Core Data/CoreDataIntakeManagerType.swift, FineDust/Core Data/CoreDataService.swift, FineDust/Core Data/CoreDataServiceType.swift, FineDust/Core Data/CoreDataUserManagerType.swift, FineDust/Dust/DustInfoManagerType.swift, FineDust/Dust/DustInfoService.swift, FineDust/Dust/DustInfoServiceType.swift, FineDust/Dust/DustObservatoryManagerType.swift, FineDust/Location/GeocoderManager.swift, FineDust/Location/GeocoderManagerType.swift, FineDust/Location/LocationManagerType.swift, FineDust/Statistics/IntakeService.swift, FineDust/Statistics/IntakeServiceType.swift, FineDust/Statistics/StatisticsViewController.swift, FineDustTests/Mock/MockDustManager.swift, FineDustTests/Mock/MockGeocoderManager.swift, FineDustTests/Test/DustInfoServiceTest.swift, FineDustTests/Test/DustManagerTest.swift, FineDustTests/Test/IntakeServiceTest.swift
=> fetch->request

FineDust.xcodeproj/project.pbxproj, FineDust/Core Data/CoreData+Intake.swift, FineDust/Core Data/CoreData+User.swift, FineDust/Core Data/CoreDataIntakeManager.swift, FineDust/Core Data/CoreDataIntakeManagerType.swift, FineDust/Core Data/CoreDataService.swift, FineDust/Core Data/CoreDataServiceType.swift, FineDust/Core Data/CoreDataUserManager.swift, FineDust/Core Data/CoreDataUserManagerType.swift, FineDust/Core Data/FineDust.xcdatamodeld/FineDust.xcdatamodel/contents, FineDust/Dust/DustInfoService.swift, FineDust/Statistics/IntakeService.swift, FineDust/Statistics/StatisticsViewController.swift, FineDust/Supporting Files/AppDelegate.swift
- 코어데이터 로직 정상화
- 미세먼지 데이터 받아올 때 0 패딩 안되던 문제 해결
=> 코어데이터 로직 변경 외

FineDust/Location/GeocoderManager.swift
=> 서울특별시 강남구 강남대로 -> 강남구 강남대로

FineDust.xcodeproj/project.pbxproj, FineDust/Common/Typealias.swift, FineDust/Core Data/CoreDataService.swift, FineDust/Core Data/CoreDataServiceType.swift, FineDust/Core Data/FineDust.xcdatamodeld/FineDust.xcdatamodel/contents, FineDust/Extension/Date+.swift, FineDust/Response/ResponseHeader.swift, FineDust/Statistics/IntakeService.swift, FineDust/Statistics/IntakeServiceType.swift, FineDust/Statistics/StatisticsViewController.swift
=> IntakeService

FineDust.xcodeproj/project.pbxproj, FineDust/HealthKit/HealthKitService.swift, FineDust/Main/Controller/MainViewController.swift
시간당 걸음거리를 구하는 메소드를 semaphore를 이용해서 구현하였습니다.
=> 시간당 걸음거리를 구하는 메소드

FineDust.xcodeproj/project.pbxproj, FineDust/Common/Typealias.swift, FineDust/Core Data/CoreDataService.swift, FineDust/Core Data/CoreDataServiceType.swift, FineDust/Core Data/FineDust.xcdatamodeld/FineDust.xcdatamodel/contents, FineDust/Extension/Date+.swift, FineDust/Response/DustResponse.swift, FineDust/Response/ResponseHeader.swift, FineDust/Statistics/IntakeService.swift, FineDust/Statistics/IntakeServiceType.swift, FineDust/Statistics/StatisticsViewController.swift, FineDustTests/Mock/MockDustManager.swift, FineDustTests/Mock/MockHealthKitManager.swift, FineDustTests/Test/DustInfoServiceTest.swift, FineDustTests/Test/DustManagerTest.swift, FineDustTests/Test/IntakeServiceTest.swift
=> 테스트 빌드 가능하게

FineDust/Main/Base.lproj/Main.storyboard, FineDust/Main/Controller/MainViewController.swift
* MainViewController 스토리 보드 작업 중입니다.
=> 스토리 보드 작업중

FineDust/HealthKit/HealthKitService.swift, FineDust/Main/Base.lproj/Main.storyboard
* 오늘 시간당 걸음거리를 구하는 메소드를 세마포어로 구현
=> 오늘 시간당 걸음거리를 구하는 메소드 변경.

FineDust/Common/Typealias.swift, FineDust/Core Data/CoreData+Intake.swift, FineDust/Core Data/CoreDataIntakeManagerType.swift, FineDust/Core Data/CoreDataService.swift, FineDust/Core Data/CoreDataServiceType.swift, FineDust/Core Data/FineDust.xcdatamodeld/FineDust.xcdatamodel/contents, FineDust/Info.plist, FineDust/Location/GeocoderManager.swift, FineDust/Statistics/IntakeService.swift, FineDust/Statistics/IntakeServiceType.swift, FineDust/Statistics/Ratio Graph/RatioGraphView.swift, FineDust/Statistics/Ratio Graph/RatioGraphView.xib, FineDust/Statistics/Ratio Graph/RatioGraphViewDelegate.swift, FineDust/Statistics/Statistics.storyboard, FineDust/Statistics/StatisticsViewController.swift, FineDust/Statistics/Value Graph/ValueGraphView.swift, FineDust/Statistics/Value Graph/ValueGraphView.xib, FineDust/Statistics/Value Graph/ValueGraphViewDelegate.swift, FineDust/Supporting Files/AppDelegate.swift, FineDustTests/Test/TestCoreDataService.swift
- 오토레이아웃
- 초미세먼지 관련 정보도 보여줌
- 4인치 대응
=> Statistics

FineDust/Info.plist, FineDust/Main/Base.lproj/Main.storyboard
* MainViewController 스토리 보드 완성 
* status bar 변경
=> MainViewController스토리 보드 작업

FineDust/Common/ProgressIndicator.swift, FineDust/HealthKit/HealthKitManager.swift, FineDust/HealthKit/HealthKitManagerType.swift, FineDust/HealthKit/HealthKitService.swift, FineDust/HealthKit/HealthKitServiceType.swift, FineDust/Main/Base.lproj/Main.storyboard, FineDust/Main/Controller/MainViewController.swift, FineDust/Network/HTTPError.swift, FineDust/Statistics/IntakeService.swift
- 페어프로그래밍!
- 네트워크 O/X | HealthKit 권한 O/X | CoreLocation 권한 O/X
- 각각 8가지 경우에 대하여 예외 처리
- CoreLocationError, HealthKitError 정의하고 ServiceErrorType 수정 필요
=> 권한 / 네트워크 예외 처리

FineDust.xcodeproj/project.pbxproj, FineDust/Common/ServiceErrorType.swift, FineDust/Core Data/CoreDataIntakeManager.swift, FineDust/Core Data/CoreDataIntakeManagerType.swift, FineDust/Core Data/CoreDataManagerType.swift, FineDust/Core Data/CoreDataService.swift, FineDust/Core Data/CoreDataUserManager.swift, FineDust/Core Data/CoreDataUserManagerType.swift, FineDust/Location/LocationError.swift, FineDust/XML/XMLError.swift
CLError에 ServiceErrorType 붙이고 구현하여 위치 권한을 얻지 못했을 때 적절한 토스트 띄움
=> 코어로케이션 에러 정의

FineDust/Statistics/StatisticsViewController.swift
=> 통계 간헐적 에러 수정

FineDust/HealthKit/HealthKitAuthorizationObserver.swift, FineDust/HealthKit/HealthKitError.swift, FineDust/HealthKit/HealthKitManager.swift, FineDust/Main/Controller/MainViewController.swift, FineDust/Response/DustGrade.swift
* 메인뷰컨트롤러에서 권한이 없을시 Health App으로 이동하는 Alert기능 구현
=> Health App으로 이동하는 Alert기능 구현

FineDust.xcodeproj/project.pbxproj, FineDust/Common/LastSavedData.swift, FineDust/Core Data/CoreDataService.swift, FineDust/Core Data/CoreDataServiceType.swift, FineDust/Core Data/FineDust.xcdatamodeld/FineDust.xcdatamodel/contents, FineDust/Main/Controller/MainViewController.swift, FineDustTests/Mock/MockCoreDataService.swift, FineDustTests/Test/TestCoreDataService.swift
- requestLastSavedData
- saveLastSteps
- saveLastDistance
- saveLastDustData
- saveLastTodayIntake
=> 코어데이터서비스 메소드 추가

FineDust/Main/Base.lproj/Main.storyboard, FineDust/Main/Controller/MainViewController.swift
* 첫 번째 화면에 권한을 체크하고 부여하는 기능을 추가했습니다.
=> 권한 부여 버튼 기능 추가

FineDust/Main/Controller/MainViewController.swift
=> 권한 부여 기능 수정

FineDust.xcodeproj/project.pbxproj, FineDust/Common/Common.storyboard, FineDust/Common/CommonTabBarController.swift, FineDust/Statistics/GraphDrawable.swift, FineDust/Statistics/IntakeRequestable.swift, FineDust/Statistics/Ratio Graph/RatioGraphView.swift, FineDust/Statistics/StatisticsViewController.swift, FineDustTests/Mock/MockIntakeService.swift, FineDustTests/Test/TestStatisticsViewController.swift
StatisticsViewController에서 사용되는 메소드도 프로토콜로 빼서 분리했고 의존성 주입하는 함수도 프로토콜에 정의해서 viewDidLoad에서 주입하도록 했는데
올바르게 한 것인지는 모르겠습니다
아무튼 IntakeRequestable 커버리지 100
=> StatisticsViewController 의존성 분리 / 테스트
